// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kongming/v1/kongming.proto

package kongmingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Objectives    []string               `protobuf:"bytes,5,rep,name=objectives,proto3" json:"objectives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DispatchRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DispatchRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DispatchRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DispatchRequest) GetObjectives() []string {
	if x != nil {
		return x.Objectives
	}
	return nil
}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ReportJson    string                 `protobuf:"bytes,4,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DispatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DispatchResponse) GetReportJson() string {
	if x != nil {
		return x.ReportJson
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Order) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Order) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateFilter   int32                  `protobuf:"varint,1,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetStateFilter() int32 {
	if x != nil {
		return x.StateFilter
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListGeneralsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGeneralsRequest) Reset() {
	*x = ListGeneralsRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGeneralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGeneralsRequest) ProtoMessage() {}

func (x *ListGeneralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGeneralsRequest.ProtoReflect.Descriptor instead.
func (*ListGeneralsRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{6}
}

type General struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Skills        []string               `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	State         int32                  `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *General) Reset() {
	*x = General{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *General) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*General) ProtoMessage() {}

func (x *General) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use General.ProtoReflect.Descriptor instead.
func (*General) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{7}
}

func (x *General) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *General) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *General) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *General) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *General) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type ListGeneralsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generals      []*General             `protobuf:"bytes,1,rep,name=generals,proto3" json:"generals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGeneralsResponse) Reset() {
	*x = ListGeneralsResponse{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGeneralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGeneralsResponse) ProtoMessage() {}

func (x *ListGeneralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGeneralsResponse.ProtoReflect.Descriptor instead.
func (*ListGeneralsResponse) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{8}
}

func (x *ListGeneralsResponse) GetGenerals() []*General {
	if x != nil {
		return x.Generals
	}
	return nil
}

type ListJinnangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJinnangRequest) Reset() {
	*x = ListJinnangRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJinnangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJinnangRequest) ProtoMessage() {}

func (x *ListJinnangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJinnangRequest.ProtoReflect.Descriptor instead.
func (*ListJinnangRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{9}
}

type Jinnang struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jinnang) Reset() {
	*x = Jinnang{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jinnang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jinnang) ProtoMessage() {}

func (x *Jinnang) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jinnang.ProtoReflect.Descriptor instead.
func (*Jinnang) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{10}
}

func (x *Jinnang) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Jinnang) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Jinnang) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Jinnang) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListJinnangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jinnangs      []*Jinnang             `protobuf:"bytes,1,rep,name=jinnangs,proto3" json:"jinnangs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJinnangResponse) Reset() {
	*x = ListJinnangResponse{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJinnangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJinnangResponse) ProtoMessage() {}

func (x *ListJinnangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJinnangResponse.ProtoReflect.Descriptor instead.
func (*ListJinnangResponse) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{11}
}

func (x *ListJinnangResponse) GetJinnangs() []*Jinnang {
	if x != nil {
		return x.Jinnangs
	}
	return nil
}

type ExecuteJinnangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJinnangRequest) Reset() {
	*x = ExecuteJinnangRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJinnangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJinnangRequest) ProtoMessage() {}

func (x *ExecuteJinnangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJinnangRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJinnangRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteJinnangRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecuteJinnangRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteJinnangRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecuteJinnangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJinnangResponse) Reset() {
	*x = ExecuteJinnangResponse{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJinnangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJinnangResponse) ProtoMessage() {}

func (x *ExecuteJinnangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJinnangResponse.ProtoReflect.Descriptor instead.
func (*ExecuteJinnangResponse) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteJinnangResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteJinnangResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteJinnangResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Inputs        map[string]string      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowRequest) Reset() {
	*x = RunWorkflowRequest{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowRequest) ProtoMessage() {}

func (x *RunWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RunWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{14}
}

func (x *RunWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RunWorkflowRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type RunWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	NodeStates    map[string]string      `protobuf:"bytes,3,rep,name=node_states,json=nodeStates,proto3" json:"node_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkflowResponse) Reset() {
	*x = RunWorkflowResponse{}
	mi := &file_kongming_v1_kongming_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowResponse) ProtoMessage() {}

func (x *RunWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kongming_v1_kongming_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RunWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_kongming_v1_kongming_proto_rawDescGZIP(), []int{15}
}

func (x *RunWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunWorkflowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunWorkflowResponse) GetNodeStates() map[string]string {
	if x != nil {
		return x.NodeStates
	}
	return nil
}

var File_kongming_v1_kongming_proto protoreflect.FileDescriptor

const file_kongming_v1_kongming_proto_rawDesc = "" +
	"\n" +
	"\x1akongming/v1/kongming.proto\x12\vkongming.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x02\n" +
	"\x0fDispatchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12C\n" +
	"\acontext\x18\x04 \x03(\v2).kongming.v1.DispatchRequest.ContextEntryR\acontext\x12\x1e\n" +
	"\n" +
	"objectives\x18\x05 \x03(\tR\n" +
	"objectives\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x10DispatchResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vreport_json\x18\x04 \x01(\tR\n" +
	"reportJson\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"6\n" +
	"\x11ListOrdersRequest\x12!\n" +
	"\fstate_filter\x18\x01 \x01(\x05R\vstateFilter\"@\n" +
	"\x12ListOrdersResponse\x12*\n" +
	"\x06orders\x18\x01 \x03(\v2\x12.kongming.v1.OrderR\x06orders\"\x15\n" +
	"\x13ListGeneralsRequest\"q\n" +
	"\aGeneral\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06skills\x18\x04 \x03(\tR\x06skills\x12\x14\n" +
	"\x05state\x18\x05 \x01(\x05R\x05state\"H\n" +
	"\x14ListGeneralsResponse\x120\n" +
	"\bgenerals\x18\x01 \x03(\v2\x14.kongming.v1.GeneralR\bgenerals\"\x14\n" +
	"\x12ListJinnangRequest\"[\n" +
	"\aJinnang\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"G\n" +
	"\x13ListJinnangResponse\x120\n" +
	"\bjinnangs\x18\x01 \x03(\v2\x14.kongming.v1.JinnangR\bjinnangs\"\xbe\x01\n" +
	"\x15ExecuteJinnangRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\x06params\x18\x02 \x03(\v2..kongming.v1.ExecuteJinnangRequest.ParamsEntryR\x06params\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x16ExecuteJinnangResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb5\x01\n" +
	"\x12RunWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12C\n" +
	"\x06inputs\x18\x02 \x03(\v2+.kongming.v1.RunWorkflowRequest.InputsEntryR\x06inputs\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x13RunWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12Q\n" +
	"\vnode_states\x18\x03 \x03(\v20.kongming.v1.RunWorkflowResponse.NodeStatesEntryR\n" +
	"nodeStates\x1a=\n" +
	"\x0fNodeStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb4\x04\n" +
	"\bKongming\x12G\n" +
	"\bDispatch\x12\x1c.kongming.v1.DispatchRequest\x1a\x1d.kongming.v1.DispatchResponse\x12<\n" +
	"\bGetOrder\x12\x1c.kongming.v1.GetOrderRequest\x1a\x12.kongming.v1.Order\x12M\n" +
	"\n" +
	"ListOrders\x12\x1e.kongming.v1.ListOrdersRequest\x1a\x1f.kongming.v1.ListOrdersResponse\x12S\n" +
	"\fListGenerals\x12 .kongming.v1.ListGeneralsRequest\x1a!.kongming.v1.ListGeneralsResponse\x12P\n" +
	"\vListJinnang\x12\x1f.kongming.v1.ListJinnangRequest\x1a .kongming.v1.ListJinnangResponse\x12Y\n" +
	"\x0eExecuteJinnang\x12\".kongming.v1.ExecuteJinnangRequest\x1a#.kongming.v1.ExecuteJinnangResponse\x12P\n" +
	"\vRunWorkflow\x12\x1f.kongming.v1.RunWorkflowRequest\x1a .kongming.v1.RunWorkflowResponseB<Z:github.com/zhuge/kongming/api/proto/kongming/v1;kongmingv1b\x06proto3"

var (
	file_kongming_v1_kongming_proto_rawDescOnce sync.Once
	file_kongming_v1_kongming_proto_rawDescData []byte
)

func file_kongming_v1_kongming_proto_rawDescGZIP() []byte {
	file_kongming_v1_kongming_proto_rawDescOnce.Do(func() {
		file_kongming_v1_kongming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kongming_v1_kongming_proto_rawDesc), len(file_kongming_v1_kongming_proto_rawDesc)))
	})
	return file_kongming_v1_kongming_proto_rawDescData
}

var file_kongming_v1_kongming_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_kongming_v1_kongming_proto_goTypes = []any{
	(*DispatchRequest)(nil),        // 0: kongming.v1.DispatchRequest
	(*DispatchResponse)(nil),       // 1: kongming.v1.DispatchResponse
	(*GetOrderRequest)(nil),        // 2: kongming.v1.GetOrderRequest
	(*Order)(nil),                  // 3: kongming.v1.Order
	(*ListOrdersRequest)(nil),      // 4: kongming.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),     // 5: kongming.v1.ListOrdersResponse
	(*ListGeneralsRequest)(nil),    // 6: kongming.v1.ListGeneralsRequest
	(*General)(nil),                // 7: kongming.v1.General
	(*ListGeneralsResponse)(nil),   // 8: kongming.v1.ListGeneralsResponse
	(*ListJinnangRequest)(nil),     // 9: kongming.v1.ListJinnangRequest
	(*Jinnang)(nil),                // 10: kongming.v1.Jinnang
	(*ListJinnangResponse)(nil),    // 11: kongming.v1.ListJinnangResponse
	(*ExecuteJinnangRequest)(nil),  // 12: kongming.v1.ExecuteJinnangRequest
	(*ExecuteJinnangResponse)(nil), // 13: kongming.v1.ExecuteJinnangResponse
	(*RunWorkflowRequest)(nil),     // 14: kongming.v1.RunWorkflowRequest
	(*RunWorkflowResponse)(nil),    // 15: kongming.v1.RunWorkflowResponse
	nil,                            // 16: kongming.v1.DispatchRequest.ContextEntry
	nil,                            // 17: kongming.v1.ExecuteJinnangRequest.ParamsEntry
	nil,                            // 18: kongming.v1.RunWorkflowRequest.InputsEntry
	nil,                            // 19: kongming.v1.RunWorkflowResponse.NodeStatesEntry
	(*timestamppb.Timestamp)(nil),  // 20: google.protobuf.Timestamp
}
var file_kongming_v1_kongming_proto_depIdxs = []int32{
	16, // 0: kongming.v1.DispatchRequest.context:type_name -> kongming.v1.DispatchRequest.ContextEntry
	20, // 1: kongming.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: kongming.v1.ListOrdersResponse.orders:type_name -> kongming.v1.Order
	7,  // 3: kongming.v1.ListGeneralsResponse.generals:type_name -> kongming.v1.General
	10, // 4: kongming.v1.ListJinnangResponse.jinnangs:type_name -> kongming.v1.Jinnang
	17, // 5: kongming.v1.ExecuteJinnangRequest.params:type_name -> kongming.v1.ExecuteJinnangRequest.ParamsEntry
	18, // 6: kongming.v1.RunWorkflowRequest.inputs:type_name -> kongming.v1.RunWorkflowRequest.InputsEntry
	19, // 7: kongming.v1.RunWorkflowResponse.node_states:type_name -> kongming.v1.RunWorkflowResponse.NodeStatesEntry
	0,  // 8: kongming.v1.Kongming.Dispatch:input_type -> kongming.v1.DispatchRequest
	2,  // 9: kongming.v1.Kongming.GetOrder:input_type -> kongming.v1.GetOrderRequest
	4,  // 10: kongming.v1.Kongming.ListOrders:input_type -> kongming.v1.ListOrdersRequest
	6,  // 11: kongming.v1.Kongming.ListGenerals:input_type -> kongming.v1.ListGeneralsRequest
	9,  // 12: kongming.v1.Kongming.ListJinnang:input_type -> kongming.v1.ListJinnangRequest
	12, // 13: kongming.v1.Kongming.ExecuteJinnang:input_type -> kongming.v1.ExecuteJinnangRequest
	14, // 14: kongming.v1.Kongming.RunWorkflow:input_type -> kongming.v1.RunWorkflowRequest
	1,  // 15: kongming.v1.Kongming.Dispatch:output_type -> kongming.v1.DispatchResponse
	3,  // 16: kongming.v1.Kongming.GetOrder:output_type -> kongming.v1.Order
	5,  // 17: kongming.v1.Kongming.ListOrders:output_type -> kongming.v1.ListOrdersResponse
	8,  // 18: kongming.v1.Kongming.ListGenerals:output_type -> kongming.v1.ListGeneralsResponse
	11, // 19: kongming.v1.Kongming.ListJinnang:output_type -> kongming.v1.ListJinnangResponse
	13, // 20: kongming.v1.Kongming.ExecuteJinnang:output_type -> kongming.v1.ExecuteJinnangResponse
	15, // 21: kongming.v1.Kongming.RunWorkflow:output_type -> kongming.v1.RunWorkflowResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kongming_v1_kongming_proto_init() }
func file_kongming_v1_kongming_proto_init() {
	if File_kongming_v1_kongming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kongming_v1_kongming_proto_rawDesc), len(file_kongming_v1_kongming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kongming_v1_kongming_proto_goTypes,
		DependencyIndexes: file_kongming_v1_kongming_proto_depIdxs,
		MessageInfos:      file_kongming_v1_kongming_proto_msgTypes,
	}.Build()
	File_kongming_v1_kongming_proto = out.File
	file_kongming_v1_kongming_proto_goTypes = nil
	file_kongming_v1_kongming_proto_depIdxs = nil
}
