// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: kongming/v1/kongming.proto

package kongmingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kongming_Dispatch_FullMethodName       = "/kongming.v1.Kongming/Dispatch"
	Kongming_GetOrder_FullMethodName       = "/kongming.v1.Kongming/GetOrder"
	Kongming_ListOrders_FullMethodName     = "/kongming.v1.Kongming/ListOrders"
	Kongming_ListGenerals_FullMethodName   = "/kongming.v1.Kongming/ListGenerals"
	Kongming_ListJinnang_FullMethodName    = "/kongming.v1.Kongming/ListJinnang"
	Kongming_ExecuteJinnang_FullMethodName = "/kongming.v1.Kongming/ExecuteJinnang"
	Kongming_RunWorkflow_FullMethodName    = "/kongming.v1.Kongming/RunWorkflow"
)

// KongmingClient is the client API for Kongming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KongmingClient interface {
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	ListGenerals(ctx context.Context, in *ListGeneralsRequest, opts ...grpc.CallOption) (*ListGeneralsResponse, error)
	ListJinnang(ctx context.Context, in *ListJinnangRequest, opts ...grpc.CallOption) (*ListJinnangResponse, error)
	ExecuteJinnang(ctx context.Context, in *ExecuteJinnangRequest, opts ...grpc.CallOption) (*ExecuteJinnangResponse, error)
	RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (*RunWorkflowResponse, error)
}

type kongmingClient struct {
	cc grpc.ClientConnInterface
}

func NewKongmingClient(cc grpc.ClientConnInterface) KongmingClient {
	return &kongmingClient{cc}
}

func (c *kongmingClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, Kongming_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kongmingClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, Kongming_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kongmingClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, Kongming_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kongmingClient) ListGenerals(ctx context.Context, in *ListGeneralsRequest, opts ...grpc.CallOption) (*ListGeneralsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGeneralsResponse)
	err := c.cc.Invoke(ctx, Kongming_ListGenerals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kongmingClient) ListJinnang(ctx context.Context, in *ListJinnangRequest, opts ...grpc.CallOption) (*ListJinnangResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJinnangResponse)
	err := c.cc.Invoke(ctx, Kongming_ListJinnang_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kongmingClient) ExecuteJinnang(ctx context.Context, in *ExecuteJinnangRequest, opts ...grpc.CallOption) (*ExecuteJinnangResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteJinnangResponse)
	err := c.cc.Invoke(ctx, Kongming_ExecuteJinnang_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kongmingClient) RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (*RunWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWorkflowResponse)
	err := c.cc.Invoke(ctx, Kongming_RunWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KongmingServer is the server API for Kongming service.
// All implementations must embed UnimplementedKongmingServer
// for forward compatibility.
type KongmingServer interface {
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	ListGenerals(context.Context, *ListGeneralsRequest) (*ListGeneralsResponse, error)
	ListJinnang(context.Context, *ListJinnangRequest) (*ListJinnangResponse, error)
	ExecuteJinnang(context.Context, *ExecuteJinnangRequest) (*ExecuteJinnangResponse, error)
	RunWorkflow(context.Context, *RunWorkflowRequest) (*RunWorkflowResponse, error)
	mustEmbedUnimplementedKongmingServer()
}

// UnimplementedKongmingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKongmingServer struct{}

func (UnimplementedKongmingServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedKongmingServer) GetOrder(context.Context, *GetOrderRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedKongmingServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedKongmingServer) ListGenerals(context.Context, *ListGeneralsRequest) (*ListGeneralsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGenerals not implemented")
}
func (UnimplementedKongmingServer) ListJinnang(context.Context, *ListJinnangRequest) (*ListJinnangResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJinnang not implemented")
}
func (UnimplementedKongmingServer) ExecuteJinnang(context.Context, *ExecuteJinnangRequest) (*ExecuteJinnangResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteJinnang not implemented")
}
func (UnimplementedKongmingServer) RunWorkflow(context.Context, *RunWorkflowRequest) (*RunWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkflow not implemented")
}
func (UnimplementedKongmingServer) mustEmbedUnimplementedKongmingServer() {}
func (UnimplementedKongmingServer) testEmbeddedByValue()                  {}

// UnsafeKongmingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KongmingServer will
// result in compilation errors.
type UnsafeKongmingServer interface {
	mustEmbedUnimplementedKongmingServer()
}

func RegisterKongmingServer(s grpc.ServiceRegistrar, srv KongmingServer) {
	// If the following call panics, it indicates UnimplementedKongmingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kongming_ServiceDesc, srv)
}

func _Kongming_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kongming_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kongming_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kongming_ListGenerals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGeneralsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).ListGenerals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_ListGenerals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).ListGenerals(ctx, req.(*ListGeneralsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kongming_ListJinnang_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJinnangRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).ListJinnang(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_ListJinnang_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).ListJinnang(ctx, req.(*ListJinnangRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kongming_ExecuteJinnang_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteJinnangRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).ExecuteJinnang(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_ExecuteJinnang_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).ExecuteJinnang(ctx, req.(*ExecuteJinnangRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kongming_RunWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KongmingServer).RunWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kongming_RunWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KongmingServer).RunWorkflow(ctx, req.(*RunWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kongming_ServiceDesc is the grpc.ServiceDesc for Kongming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kongming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kongming.v1.Kongming",
	HandlerType: (*KongmingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _Kongming_Dispatch_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _Kongming_GetOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _Kongming_ListOrders_Handler,
		},
		{
			MethodName: "ListGenerals",
			Handler:    _Kongming_ListGenerals_Handler,
		},
		{
			MethodName: "ListJinnang",
			Handler:    _Kongming_ListJinnang_Handler,
		},
		{
			MethodName: "ExecuteJinnang",
			Handler:    _Kongming_ExecuteJinnang_Handler,
		},
		{
			MethodName: "RunWorkflow",
			Handler:    _Kongming_RunWorkflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kongming/v1/kongming.proto",
}
